<!-- Accordion card -->
<div class="card mt-4">
    <!-- Card header -->
    <div class="card-header" role="tab" id="headingIntlFlightTerms">
        <a class="collapsed" 
            data-toggle="collapse" 
            data-parent="#accordionEx" 
            href="#collapseIntlFlightTerms"
            aria-expanded="false" 
            aria-controls="collapseIntlFlightTerms"
        >
            <h5 class="mb-0">
                <i class="fa fa-angle-down rotate-icon orange"></i>
                قوانین پرواز خارجی
            </h5>
        </a>
    </div>

    <!-- Card body -->
    <div id="collapseIntlFlightTerms" class="collapse" role="tabpanel" aria-labelledby="headingIntlFlightTerms" data-parent="#accordionEx">
        <div class="card-body">
            <?= $this->render('_list.phtml') ?>
        </div>
    </div>
</div>
<!-- Accordion card -->
