<?php $block = isset($block) ? $block : new \app\modules\Codnitive\Checkout\blocks\Payment; ?>
<form id="checkout_payment_methods" action="<?= $block->getAction() ?>" method="post">
    <?= tools()->getCsrfInput() ?>
    <div class="info-box__discount info-box__item">
        <?= $this->render('payment/methods.phtml') ?>  
        <hr>
        <div class="row bill-box justify-content-center py-2 mt-4 payment-totals-wrapper mx-0">
            <div class="info-box__price info-box__item grand-total col-12">
                <div class="item-price">
                    <span class="item-price__label"><?= __('template', 'Grand Total') ?>:&emsp13;</span>
                    <span class="price__amount-price credit-total"><?= $block->getGrandTotal() ?></span>
                </div>
            </div>
            <?php if ($block->getCouponDiscountAmount()): ?>
            <div class="info-box__price info-box__item coupon-discount-amount col-12">
                <div class="item-price">
                    <span class="item-price__label"><?= __('template', 'Coupon Code') ?>:&emsp13;</span>
                    <span class="price__amount-price discount-total"><?= $block->getCouponDiscountAmount(false) ?></span>
                </div>
            </div>
            <?php endif ?>
            <div class="info-box__price info-box__item used-credit-total col-12 hidden">
                <div class="item-price">
                    <span class="item-price__label"><?= __('template', 'Used Credit') ?>:&emsp13;</span>
                    <span class="price__amount-price credit-total-price"></span>
                </div>
            </div>
            <div class="info-box__price info-box__item online-payable-grand-total col-12">
                <div class="item-price">
                    <span class="item-price__label"><?= __('template', 'Payable Total') ?>:&emsp13;</span>
                    <span class="price__amount-price grand-total-price"><?= $block->getPayableGrandTotal() ?></span>
                </div>
            </div>
        </div>  
        <div class="d-flex justify-content-end mb-3 col-12 mt-3 checkout-button">
            <button type="submit" 
                id="checkout_submit_button" 
                class="btn <?= $block->getButtonClass() ?> btn-full-color col-6 col-sm-4 col-lg-12 submit-button"
            >
                <?= __('template', 'Pay') ?>
            </button>
            <script type="text/javascript">
                $('body').on('click', '#checkout_submit_button', function () {
                    var btn = $(this);
                    btn.prop('disabled', true);
                    btn.addClass('disabled');
                    $('#checkout_payment_methods').submit();
                });
            </script>
        </div>
    </div>
</form>
