<!-- Modal -->
<div class="modal fade" id="validateConfirmModal" tabindex="-1" role="dialog" aria-labelledby="validateConfirmModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="validateConfirmModalLabel"><?= $title ?></h5>
      </div>
      <div class="modal-body">
        <?= $content ?>
      </div>
      <div class="modal-footer">
        <?php if (isset($cancelationUrl) && !empty($cancelationUrl)): ?>
        <a class="btn btn-secondary color-white" onclick="location = '<?= $cancelationUrl ?>'"><?= __('checkout', 'Review') ?></a>
        <?php endif ?>
        <?php if (isset($confirmUrl) && !empty($confirmUrl)): ?>
        <a class="btn btn-primary color-white" onclick="location.reload()"><?= __('checkout', 'Confirm to Payment') ?></a>
        <?php endif ?>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $(window).on('load',function(){
        $('#validateConfirmModal').modal({
            backdrop: 'static',
            keyboard: false
        });
    });
</script>
