<div role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true" id="circulation_modal"
     data-backdrop="static"
     data-keyboard="true" class="modal" tabindex="100000000"
     style="display: none; padding-right: 19px;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header " style="overflow: hidden">
                <h5 class="modal-title"
                    style="display: inline-block;"><?= __('officeautomation', 'LetterCirculation') ?></h5>
                <button type="button"
                        style="float: left;opacity: 1"
                        class="close cl_search circulation_modal_closed"
                        data-dismiss="modal"
                        aria-hidden="true"
                        aria-label="Close"
                >
                    <i style="opacity: 1;" class="fa fa-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <div id="circulation_modal_box">
                </div>
            </div>
        </div>
    </div>
</div>
