<?php

namespace app\modules\Codnitive\OfficeAutomation\models;

use yii\db\ActiveRecord;

class User extends ActiveRecord implements \yii\web\IdentityInterface
{

    public static function tableName()
    {
        return 'Users'; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        /*        foreach (self::$users as $user) {
                    if ($user['accessToken'] === $token) {
                        return new static($user);
                    }
                }*/

        return null;
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username, $password)
    {
        $findUser = static::findOne(['UserUserName' => $username, 'UserPassword' => $password, 'UserActivity' => 1]);
        if ($findUser) {
            $session = \Yii::$app->session;
            $session->set('UserID',$findUser->UserID);
            $session->set('UserSign',$findUser->UserSign);
            return $findUser;
        } else {
            return null;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->UserID;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->authKey === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        $findUser = Users::findOne(['UserPassword' => $password]);
        if ($findUser) {
            return true;
        } else {
            return null;
        }
    }
}
