<div class="home2"></div>

<div class="clearfix"></div>
<section class="mb-0 mt-5">
    <div class="container">
        <div class="col-12 text-justify col-md-10 col-xl-8 text-lg-left offset-md-1 offset-xl-2 pt-md-5">
            <p> مجموعه رابین پردازش آریا، فعالیت خود را از سال 1398 آغاز کرده است. </p>
            <p>تاسیس شرکت، حاصل تجربه ایجاد راهکارهای نرم افزاری بر پایه توسعه، طراحی و تحلیل + نیاز کسب و کارها بوده است.</p>
            <p>این متن در حال تکمیل است.</p>
        </div>
    </div>
</section>
