<section class="section-full">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-map-marker"></span><br>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Address') ?></h5>
                        </div>
                        <div class="package text-center">
                            <div class="price"></div>
                            <span class="text-white"><?= __('template', 'HQ2_Address') ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-phone"></span><br>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Phone') ?></h5>
                        </div>
                        <div class="package text-center">
                            <div class="price"></div>
                            <span class="text-white"><?= __('template', '0912&nbsp;847&nbsp;62&nbsp;13&nbsp;') ?></span>
                            <br>
                            <span class="text-white"><?= __('template', '0912&nbsp;204&nbsp;07&nbsp;74&nbsp;') ?></span>
                        </div>
                    </div>
                </div>
            </div>
                <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-fax"></span><br>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Fax') ?></h5>
                        </div>
                        <div class="package text-center">
                            <span class="text-white"><?= __('template', '35632088') ?></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-xs-12 col-lg-3 col-md-6 mt-2">
                <div class="single-pricing-table">
                    <div class="top">
                        <div class="head text-center">
                            <span class="fa fa-envelope"></span>
                            <h5 class="text-white text-uppercase"><?= __('template', 'Email') ?></h5>
                        </div>
                        <div class="package text-center">
                            <div class="price"></div>
                            <span class="text-white"><?= __('template', 'neatland@gmail.com') ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>