<section class="section-full-small mt-5 align-items-center d-flex contact-info">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6 contact-row">
				<div class="package text-center">
					<span class="fa fa-map-marker  fz-20  ml-0 mr-2 orang"></span>
					<span class="text-white fz-12 footer-address"><?= __('template', 'HQ2_Address') ?></span>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 contact-row">
				<div class="package text-center">
					<span class="fa fa-phone  fz-20  ml-0 mr-2 orang"></span>
					<span class="text-white"><?= __('template', '0912&nbsp;847&nbsp;62&nbsp;13&nbsp;') ?> | <?= __('template', '0912&nbsp;204&nbsp;07&nbsp;74&nbsp;') ?></span>
				</div>
			</div>
			<div class="col-lg-2 col-md-6 contact-row">
				<div class="package text-center">
					<span class="fa fa-fax  fz-20  ml-0 mr-2 orang"></span>
					<span class="text-white"><?= __('template', '0912&nbsp;204&nbsp;07&nbsp;74&nbsp;') ?></span>
				</div>
			</div>
			<div class="col-lg-3 col-md-6 contact-row">
				<div class="package text-center">
					<span class="fa fa-envelope fz-20 ml-0 mr-2 orang"></span>
					<span class="text-white"><?= __('template', 'neatland@gmail.com') ?></span>
				</div>
			</div>
		</div>
	</div>
</section>
