<div class="copyright">
    <div class="container d-flex flex-column flex-md-row justify-content-between">
        <?= $this->render('social.phtml') ?>
        <div class="py-0 mx-3">
            <div class="copyright_content text-center d-flex flex-lg-row flex-column align-items-lg-center justify-content-center">
                <div class="cr">
                    Copyright ©
                    <script>
                        document.write(new Date().getFullYear());
                    </script> - 2019
                    All rights reserved | Made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://nugig.com" target="_blank">NUGIG</a>
                </div>
            </div>
        </div>
    </div>
</div>

