<div class="social-row m-0 py-3">
    <?php /*<h2><?= __('template', 'You can share this page with your firends') ?></h2>*/ ?>
    <div class="footer_social ml-lg-auto mt-4 ">
        <ul>
            <li><a href="https://www.aparat.com/nugig" target="_blank"><i class="fab icon-film aparat"></i></a></li>
            <li><a href="https://www.instagram.com/nugig/" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://www.pinterest.com/nugig/" target="_blank"><i class="fab fa-pinterest-p"></i></a></li>
            <li><a href="https://twitter.com/nugig" target="_blank"><i class="fab fa-twitter"></i></a></li>
            <?php /*<li><a href="#"><i class="fab fa-dribbble"></i></a></li>
            <li><a href="#"><i class="fab fa-behance"></i></a></li>
            <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>*/ ?>
        </ul>
    </div>
</div>
