<div class="container go-path-info">
    <div class="mb-3 box-result-roundtrip d-flex flex-column flex-md-row justify-content-between gray-back align-items-center p-3 p-lg-0">
        <div class="py-2  px-3 d-flex flex-wrap">
            <div class="d-flex align-items-center align-items-center justify-content-center item-search logo m-0">
            <?php $logoImg = $data['airline_iata'] ?>
            <?php if ($logoImg): ?>
                <img src="<?= tools()->getMediaUrl("flight/$logoImg.png") ?>" alt="<?= $data['airline'] ?>">
            <?php else: ?>
                <i class="icon-airplane" style="transform: rotatey(180deg); color: #ccc;"></i>
            <?php endif; ?>
            </div>
            <span class="res-search d-inline-flex mr-2 align-items-center justify-content-center">
                <?php //__('flight', '<span class="path-title ml-1">First flight from </span>{origin_name} to {destination_name} ({flight_number})', $data) ?>
                <?= __('flight', '<span class="path-title ml-1">First flight from </span>{origin_name} to {destination_name}', $data) ?>
            </span>
        </div>

        <?php $date = str_replace('-', '/', $data['departure_date_persian']) ?>
        <div class="py-2  px-3 d-inline-flex align-items-center justify-content-center">
            <span class="d-lg-inline-flex mr-1 align-items-center justify-content-center d-none"><?= __('template', 'Date') ?>: </span>
            <span class="d-inline-flex align-items-center justify-content-center"><?= $date ?></span>
        </div>
        <div class="py-2  px-3 d-inline-flex align-items-center justify-content-center">
            <span class="d-lg-inline-flex mr-1 align-items-center justify-content-center d-none"><?= __('template', 'Time') ?>: </span>
            <span class="d-inline-flex align-items-center justify-content-center"><?= $data['departure_time'] ?></span>
        </div>

        <div class="py-2  px-3 d-flex">
            <span class="d-none d-lg-inline-block"><?= __('template', 'Price') ?>:&nbsp;</span>
            <span class="price"><?= tools()->formatRial($data['final_price']) ?></span>
        </div>
        <div class="py-2  px-3  d-flex search-again">
            <a href="<?= $changeGoingFlightUrl ?>" class="text-white"><?= __('flight', 'Change going path flight') ?><i class="fa fa-search mr-2"></i></a>
        </div>
    </div>
</div>
