<section>
    <div class="blue"><h4 class="mb-3 color">تیتر</h4></div>
    <ol class="col-12 mt-2 p-1 p-sm-2 mr-sm-1 p-md-3 mr-md-2 p-lg-4 mr-lg-3 text-justify text-lg-left orange">
        <li class="mb-3">قانون</li>
    </ol>
</section>

<section class="mt-5 blue">
    <h4 class="mb-3 color">تیتر</h4>
    <p>پاراگراف</p>
    <ol class="col-12 mt-2 p-1 p-sm-2 mr-sm-1 p-md-3 mr-md-2 p-lg-4 mr-lg-3 text-justify text-lg-left">
        <li class="mb-3">قانون</li>
    </ol>
</section>
