<!-- Accordion card -->
<div class="card mt-4">
    <!-- Card header -->
    <div class="card-header" role="tab" id="headingFlightTerms">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseFlightTerms"
        aria-expanded="false" aria-controls="collapseFlightTerms">
        <h5 class="mb-0"><i class="fa fa-angle-down rotate-icon orange"></i>
            مورد 3
        </h5>
        </a>
    </div>

    <!-- Card body -->
    <div id="collapseFlightTerms" class="collapse" role="tabpanel" aria-labelledby="headingFlightTerms" data-parent="#accordionEx">
        <div class="card-body">
            <?= $this->render('_list.phtml') ?>
        </div>
    </div>
</div>
<!-- Accordion card -->
