<!-- Accordion card -->
<div class="card mt-4">
    <!-- Card header -->
    <div class="card-header" role="tab" id="headingDomsFlightTerms">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseDomsFlightTerms"
        aria-expanded="false" aria-controls="collapseDomsFlightTerms">
        <h5 class="mb-0"><i class="fa fa-angle-down rotate-icon orange"></i>
            مورد 2
        </h5>
        </a>
    </div>

    <!-- Card body -->
    <div id="collapseDomsFlightTerms" class="collapse" role="tabpanel" aria-labelledby="headingDomsFlightTerms" data-parent="#accordionEx">
        <div class="card-body">
            <?= $this->render('_list.phtml') ?>
        </div>
    </div>
</div>
<!-- Accordion card -->
