<!-- Messages: style can be found in dropdown.less-->
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-envelope-o"></i>
        <span class="label label-success">4</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">۴ پیام خوانده نشده</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li><!-- start message -->
                    <a href="#">
                        <div class="pull-right">
                            <img src="<?= tools()->getImageUrl('/icons/user8.png') ?>" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            علیرضا
                            <small><i class="fa fa-clock-o"></i> ۵ دقیقه پیش</small>
                        </h4>
                        <p>متن پیام</p>
                    </a>
                </li>
                <!-- end message -->

            </ul>
        </li>
        <li class=""><a href="#">نمایش تمام پیام ها</a></li>
    </ul>
</li>
<!-- Notifications: style can be found in dropdown.less -->