<li class="dropdown notifications-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <span class="label label-warning">۱۰</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">۱۰ اعلان جدید</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li>
                    <a href="#">
                        <i class="fa fa-users text-aqua"></i> ۵ کاربر جدید ثبت نام کردند
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-warning text-yellow"></i> اخطار دقت کنید
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-users text-red"></i> ۴ کاربر جدید ثبت نام کردند
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-shopping-cart text-green"></i> ۲۵ سفارش جدید
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-user text-red"></i> نام کاربریتان را تغییر دادید
                    </a>
                </li>
            </ul>
        </li>
        <li class=""><a href="#">نمایش همه</a></li>
    </ul>
</li>
<!-- Tasks: style can be found in dropdown.less -->